import Link from "next/link";
import { Nav } from "@/components/Nav";

export default function HomePage() {
  return (
    <div className="paper-grid min-h-screen">
      <Nav active="home" />
      <main className="mx-auto max-w-6xl px-6 py-16">
        <p className="text-sm uppercase tracking-[0.2em] text-clay">A maker studio</p>
        <h1 className="mt-3 max-w-3xl font-display text-5xl leading-tight md:text-7xl">
          Cross-stitch that gets harder on purpose. Clay that starts at the beginning.
        </h1>
        <p className="mt-6 max-w-2xl text-lg text-ink/70">
          Aida uses a supervisor agent and four specialists. The chart itself is not generated by an LLM —
          photos become DMC patterns with perceptual color matching, then the coach helps you pick a stretch
          project.
        </p>
        <div className="mt-12 grid gap-6 md:grid-cols-2">
          <StudioCard
            href="/stitch"
            kicker="For stitchers with miles on the needle"
            title="Cross-stitch studio"
            body="Convert a photo, read a difficulty score, and ask the coach for the next harder pattern — not a 50-color confetti leap."
          />
          <StudioCard
            href="/clay"
            kicker="Never used clay? Start here"
            title="Clay studio"
            body="Seven short how-tos: knead, make a bowl, stick pieces on, then a cup or a tile. Everyday words, not studio jargon."
          />
        </div>
      </main>
    </div>
  );
}

function StudioCard({
  href,
  kicker,
  title,
  body,
}: {
  href: string;
  kicker: string;
  title: string;
  body: string;
}) {
  return (
    <Link
      href={href}
      className="group rounded-3xl border border-ink/10 bg-white/80 p-8 shadow-card transition hover:-translate-y-0.5"
    >
      <p className="text-xs uppercase tracking-wide text-moss">{kicker}</p>
      <h2 className="mt-2 font-display text-3xl group-hover:text-thread">{title}</h2>
      <p className="mt-3 text-ink/70">{body}</p>
    </Link>
  );
}
